/*
 * Registry API
 * The Registry service allows teams to manage descriptions of APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiDeployment
 */
public class ApiDeploymentTest {
    private final ApiDeployment model = new ApiDeployment();

    /**
     * Model tests for ApiDeployment
     */
    @Test
    public void testApiDeployment() {
        // TODO: test ApiDeployment
    }

    /**
     * Test the property 'accessGuidance'
     */
    @Test
    public void accessGuidanceTest() {
        // TODO: test accessGuidance
    }

    /**
     * Test the property 'annotations'
     */
    @Test
    public void annotationsTest() {
        // TODO: test annotations
    }

    /**
     * Test the property 'apiSpecRevision'
     */
    @Test
    public void apiSpecRevisionTest() {
        // TODO: test apiSpecRevision
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'endpointUri'
     */
    @Test
    public void endpointUriTest() {
        // TODO: test endpointUri
    }

    /**
     * Test the property 'externalChannelUri'
     */
    @Test
    public void externalChannelUriTest() {
        // TODO: test externalChannelUri
    }

    /**
     * Test the property 'intendedAudience'
     */
    @Test
    public void intendedAudienceTest() {
        // TODO: test intendedAudience
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'revisionCreateTime'
     */
    @Test
    public void revisionCreateTimeTest() {
        // TODO: test revisionCreateTime
    }

    /**
     * Test the property 'revisionId'
     */
    @Test
    public void revisionIdTest() {
        // TODO: test revisionId
    }

    /**
     * Test the property 'revisionUpdateTime'
     */
    @Test
    public void revisionUpdateTimeTest() {
        // TODO: test revisionUpdateTime
    }

}
