/*
 * Registry API
 * The Registry service allows teams to manage descriptions of APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ApiDeployment;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListApiDeploymentsResponse
 */
public class ListApiDeploymentsResponseTest {
    private final ListApiDeploymentsResponse model = new ListApiDeploymentsResponse();

    /**
     * Model tests for ListApiDeploymentsResponse
     */
    @Test
    public void testListApiDeploymentsResponse() {
        // TODO: test ListApiDeploymentsResponse
    }

    /**
     * Test the property 'apiDeployments'
     */
    @Test
    public void apiDeploymentsTest() {
        // TODO: test apiDeployments
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

}
