/*
 * Registry API
 * The Registry service allows teams to manage descriptions of APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ApiSpec;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListApiSpecsResponse
 */
public class ListApiSpecsResponseTest {
    private final ListApiSpecsResponse model = new ListApiSpecsResponse();

    /**
     * Model tests for ListApiSpecsResponse
     */
    @Test
    public void testListApiSpecsResponse() {
        // TODO: test ListApiSpecsResponse
    }

    /**
     * Test the property 'apiSpecs'
     */
    @Test
    public void apiSpecsTest() {
        // TODO: test apiSpecs
    }

    /**
     * Test the property 'nextPageToken'
     */
    @Test
    public void nextPageTokenTest() {
        // TODO: test nextPageToken
    }

}
