/*
 * Registry API
 * The Registry service allows teams to manage descriptions of APIs.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ApiSpec;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Response message for ListApiSpecs.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T15:41:51.178072+05:30[Asia/Kolkata]", comments = "Generator version: 7.15.0")
public class ListApiSpecsResponse {
  public static final String SERIALIZED_NAME_API_SPECS = "apiSpecs";
  @SerializedName(SERIALIZED_NAME_API_SPECS)
  @javax.annotation.Nullable
  private List<ApiSpec> apiSpecs = new ArrayList<>();

  public static final String SERIALIZED_NAME_NEXT_PAGE_TOKEN = "nextPageToken";
  @SerializedName(SERIALIZED_NAME_NEXT_PAGE_TOKEN)
  @javax.annotation.Nullable
  private String nextPageToken;

  public ListApiSpecsResponse() {
  }

  public ListApiSpecsResponse apiSpecs(@javax.annotation.Nullable List<ApiSpec> apiSpecs) {
    this.apiSpecs = apiSpecs;
    return this;
  }

  public ListApiSpecsResponse addApiSpecsItem(ApiSpec apiSpecsItem) {
    if (this.apiSpecs == null) {
      this.apiSpecs = new ArrayList<>();
    }
    this.apiSpecs.add(apiSpecsItem);
    return this;
  }

  /**
   * The specs from the specified publisher.
   * @return apiSpecs
   */
  @javax.annotation.Nullable
  public List<ApiSpec> getApiSpecs() {
    return apiSpecs;
  }

  public void setApiSpecs(@javax.annotation.Nullable List<ApiSpec> apiSpecs) {
    this.apiSpecs = apiSpecs;
  }


  public ListApiSpecsResponse nextPageToken(@javax.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  /**
   * A token, which can be sent as &#x60;page_token&#x60; to retrieve the next page. If this field is omitted, there are no subsequent pages.
   * @return nextPageToken
   */
  @javax.annotation.Nullable
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(@javax.annotation.Nullable String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListApiSpecsResponse listApiSpecsResponse = (ListApiSpecsResponse) o;
    return Objects.equals(this.apiSpecs, listApiSpecsResponse.apiSpecs) &&
        Objects.equals(this.nextPageToken, listApiSpecsResponse.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiSpecs, nextPageToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListApiSpecsResponse {\n");
    sb.append("    apiSpecs: ").append(toIndentedString(apiSpecs)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("apiSpecs", "nextPageToken"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListApiSpecsResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListApiSpecsResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListApiSpecsResponse is not found in the empty JSON string", ListApiSpecsResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListApiSpecsResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListApiSpecsResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("apiSpecs") != null && !jsonObj.get("apiSpecs").isJsonNull()) {
        JsonArray jsonArrayapiSpecs = jsonObj.getAsJsonArray("apiSpecs");
        if (jsonArrayapiSpecs != null) {
          // ensure the json data is an array
          if (!jsonObj.get("apiSpecs").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `apiSpecs` to be an array in the JSON string but got `%s`", jsonObj.get("apiSpecs").toString()));
          }

          // validate the optional field `apiSpecs` (array)
          for (int i = 0; i < jsonArrayapiSpecs.size(); i++) {
            ApiSpec.validateJsonElement(jsonArrayapiSpecs.get(i));
          };
        }
      }
      if ((jsonObj.get("nextPageToken") != null && !jsonObj.get("nextPageToken").isJsonNull()) && !jsonObj.get("nextPageToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nextPageToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextPageToken").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListApiSpecsResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListApiSpecsResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListApiSpecsResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListApiSpecsResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ListApiSpecsResponse>() {
           @Override
           public void write(JsonWriter out, ListApiSpecsResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListApiSpecsResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListApiSpecsResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListApiSpecsResponse
   * @throws IOException if the JSON string is invalid with respect to ListApiSpecsResponse
   */
  public static ListApiSpecsResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListApiSpecsResponse.class);
  }

  /**
   * Convert an instance of ListApiSpecsResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

